version: 1
default_environment: dev
project_id: 5fc7fe95-0ab1-40fd-b4fb-9ae740015134
environments:
- name: dev
- name: staging
- name: prod
plugins:
  extractors:
  - name: tap-csv
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-csv.git
    config:
      files:
      - entity: order-detail
        path: ../data/order_details.csv
        keys: [order_id, product_id, unit_price, quantity, discount]
  - name: tap-postgres
    variant: meltanolabs
    pip_url: git+https://github.com/MeltanoLabs/tap-postgres.git
    config:
      port: 5432
      host: localhost
      user: northwind_user
      database: northwind
      stream_maps:
        public-orders:
          freight: str(record['freight'])
        public-products:
          unit_price: str(record['unit_price'])
  loaders:
  - name: target-jsonl
    variant: andyh1203
    pip_url: target-jsonl
  - name: target-postgres
    variant: meltanolabs
    pip_url: meltanolabs-target-postgres
    config:
      user: meltano
      database: lighthouse
      host: localhost
      port: 5555
  mappers:
  - name: meltano-map-transformer
    variant: meltano
    pip_url: git+https://github.com/MeltanoLabs/meltano-map-transform.git
jobs:
- name: extract-postgres
  tasks:
  - tap-postgres target-jsonl
- name: extract-csv
  tasks:
  - tap-csv target-jsonl
